### ISSUE TITLE
cell display become distorted after rotation

### ISSUE THREAD

**Issue by velociraptor111** [amerhukic/SwipeableCollectionViewCell-Example#2] opened 2019-07-10 20:12 UTC
Thanks for writing this code, I notice after downloading and running your project that after rotating the device, random cells in the uicollectionview will get distorted like so
![IMG_624763DF0FC9-1](https://user-images.githubusercontent.com/19272937/61001333-71d2b180-a32d-11e9-9961-464e837af905.jpeg)

Do you know what might cause it? Thanks again

**Comment by texyz** [comment] 2019-07-20 09:29
Please does Didselect work for you?

**Comment by velociraptor111** [comment] 2019-07-20 13:57
no it doesn't, I had to implement my own tap gesture recognizer

**Comment by texyz** [comment] 2019-07-20 14:05
Please can you share me how you achieved that, please

**Comment by velociraptor111** [comment] 2019-07-20 14:09
Can you setup a different issue and we can answer it there? Just so that this original problem doesn't get cluttered and off topic

**Comment by texyz** [comment] 2019-07-20 14:11
Okay, many thanks

**Comment by texyz** [comment] 2019-07-20 18:01
> Please see issue raised below, thanks so much
https://github.com/amerhukic/SwipeableCollectionViewCell-Example/issues/3 <https://github.com/amerhukic/SwipeableCollectionViewCell-Example/issues/3>

**Comment by amerhukic** [comment] 2019-07-20 22:19
@velociraptor111 I will take a look at the issue and get back to you.

**Comment by amerhukic** [comment] 2019-07-21 21:18
Hi @velociraptor111! The issue is fixed in the last commit. The problem was that the scrollview content offset was not updated when the orientation changes and the cell becomes wider. Thank you for reporting the issue.

**Closed as completed by amerhukic** 2019-07-21 21:18 UTC
